openapi: 3.0.0
info:
  title: Todos API
  description: API documentation for managing todos and items
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
tags:
  - name: Authentication
    description: User authentication
  - name: Todos
    description: Operations related to todos
  - name: Items
    description: Operations related to todo items
paths:
  paths:
  /auth/login:
    post:
      summary: Authenticate user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Authentication successful, returns JWT token
  /signup:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
      responses:
        "201":
          description: User registered successfully
  /todos:
    get:
      summary: Get all todos
      tags:
        - Todos
      security:
        - bearerAuth: [] 
      responses:
        "200":
          description: A list of todos
        "401":
          description: Unauthorized - Missing or invalid token
    post:
      summary: Create a new todo
      tags:
        - Todos
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                created_by:
                  type: integer
      responses:
        "201":
          description: Todo created successfully
        "401":
          description: Unauthorized - Missing or invalid token
  /todos/{todo_id}:
    put:
      summary: Update a todo
      tags:
        - Todos
      security:
        - bearerAuth: []
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        "200":
          description: Todo updated successfully
    delete:
      summary: Delete a todo
      tags:
        - Todos
      security:
        - bearerAuth: []
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Todo deleted successfully
  /todos/{todo_id}/items:
    get:
      summary: Get all items for a todo
      tags:
        - Items
      security:
        - bearerAuth: []
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A list of items
    post:
      summary: Create a new item for a todo
      tags:
        - Items
      security:
        - bearerAuth: []
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                done:
                  type: boolean
      responses:
        "201":
          description: Item created successfully
  /todos/{todo_id}/items/{id}:
    put:
      summary: Update an item
      tags:
        - Items
      security:
        - bearerAuth: []
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: integer
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                done:
                  type: boolean
      responses:
        "200":
          description: Item updated successfully
    delete:
      summary: Delete an item
      tags:
        - Items
      security:
        - bearerAuth: []
      parameters:
        - name: todo_id
          in: path
          required: true
          schema:
            type: integer
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Item deleted successfully
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
